jontoye/ai-adventure

client/src/components/BackgroundStory.jsx, server/models/Character.js
Define character by name, class, strength and weakness.
Write your own backstory or have the AI create one!
=> rework character creation and backstory generation

client/src/components/Adventure.jsx, client/src/components/CreateAdventure.jsx, client/src/components/CreateCharacter.jsx, client/src/components/Entry.jsx
Minor fixes and a backup before major changes
=> failed attempt to fix new line in create adevnture

client/src/App.js, client/src/components/Banner.jsx, client/src/components/CreateCharacter.jsx, client/src/components/Home.jsx, client/src/data/character.js
You can now edit the AI generated backstory before submitting, along with the randomly generated character created via quickstart!
=> Quickstartdefaults

client/src/App.js, client/src/App.scss, client/src/components/Adventure.jsx, client/src/components/Banner.css, client/src/components/Banner.jsx, client/src/components/CreateCharacter.jsx, client/src/data/character.js
=> style changes, sleepy

client/src/App.js, client/src/components/Adventure.jsx, client/src/components/CreateAdventure.jsx, client/src/data/character.js
figured out how to send props through links fairly easily! sending data to adventure from create adventure now
=> Link to adventure after creating adventure with props passed

client/src/components/CreateAdventure.jsx, client/src/components/CreateCharacter.jsx
Character create links to adventure create with character defaulting to newest.
=> Adventure work

client/src/components/Adventure.jsx, client/src/components/CreateAdventure.jsx, client/src/components/CreateCharacter.jsx
Passed name to adventure/create adventure to improve prompts
=> Prompt imrovement

client/src/App.js, client/src/components/Profile.jsx, client/src/index.css
Previous navbar links were causing page refreshes. No more page refreshes now, much faster performance.
=> fix navbar links to not cause page refresh

client/src/App.js, client/src/App.scss, client/src/components/CharacterDetail.jsx
Added char detail page, slight navbar tweak
=> Char detail

client/src/components/CharacterDetail.jsx, client/src/components/Profile.jsx, client/src/components/css/CharacterDetail.css, client/src/components/css/Profile.css, client/src/components/css/ProfileImage.css
Fixed character details page and change profile image modal
=> fixed character details page, mostly

client/src/components/AdventureInfo.jsx, client/src/components/Character.jsx, client/src/components/CharacterDetail.jsx, client/src/components/css/AdventureInfo.css, client/src/components/css/Character.css
=> style changes, minor fixes

client/src/components/Adventure.jsx, client/src/components/Entry.jsx, client/src/components/css/Entry.css
=> prevent unwanted button pressing

client/src/App.scss, client/src/components/css/CreateAdventure.css
=> drop down fix

client/src/App.js, server/models/Achievement.js, server/models/User.js
=> mostly images

client/src/App.js, client/src/components/CreateAdventure.jsx, client/src/components/CreateCharacter.jsx, client/src/data/character.js
=> achievment framework added

client/src/components/Adventure.jsx, client/src/components/CreateAdventure.jsx, client/src/components/Entry.jsx, client/src/components/css/Adventure.css, client/src/components/css/Entry.css, server/package-lock.json, server/package.json, server/server.js
Attempt to fix our crashing error. Css update partially complete.
=> Timeout test

client/src/components/css/Entry.css
=> animation fix

client/src/components/Adventure.jsx
attempt at input length fix error 400
=> attempt at input length fix

client/src/components/Adventure.jsx, client/src/components/Entry.jsx, client/src/components/css/Adventure.css, client/src/components/css/Entry.css
style changes to adventure.jsx, repetition bug fix attempt
=> Prompt work

client/src/components/Adventure.jsx, client/src/data/character.js
=> removed options from prompt

client/src/components/Character.jsx
Name should change in backstory now for most cases
=> char copy name replacement fix

client/src/App.js, client/src/components/AdventureInfo.jsx, client/src/components/Adventures.jsx, client/src/components/Banner.jsx, client/src/components/CreateAdventure.jsx
Continued achievement work, bug with passing function to copy adventure
=> Broke something

client/src/App.js, client/src/components/AdventureInfo.jsx, client/src/components/Banner.jsx, client/src/components/Character.jsx, client/src/components/Characters.jsx, client/src/components/CreateCharacter.jsx, client/src/components/ImageSelect.jsx, client/src/components/css/PictureChanger.css, client/src/user/Signup.jsx
Image Select Screen after user creation
=> Image Select Screen after user creation

client/src/components/Character.jsx
=> char copy fix

README.md
readme checkmarks on todo list
=> readme checkmarks on todo list
